### PR TITLE
Eslint files fix

### PR DESCRIPTION
**Pull request by wissog**
see maybe we don't need that .prepush.eslintrc.json file anymore...

### CODE REVIEW

**Review by gshilin — APPROVED** [review]

**Comment by wissog** [comment]
converted FallbackImage
see whether we need the internal image object

**Comment by gshilin-sdb** [comment]
This PR was merged yesterday. Please create a new one

**Comment by wissog** [comment]
I did

**Comment by gshilin** [comment]
[image: image.png]

It was merged yesterday and deleted. Please create a new local branch based
on this one and create a PR from the new one.

**Comment by gshilin-sdb** [comment]
It is a one you're talking about?

**Comment by wissog** [comment]
Yeah

**Pull request merged**
